remote_theme: aterenin/minima-reboot
footer_icons:
  - username: Mostly Good Ideas 
    url: https://mostlygoodideas.nz/
  - username: Daylight Differentials
     url: https://daylightdifferentials.wordpress.com/
  - username: The Spinoff
     url: https://thespinoff.co.nz/authors/shanti-mathias
